version: "3"

services:
  front:
    build: ./frontend
    image: gql-frontend:gql-frontend_v1
    ports:
      - 1234:3000
  back:
    build: ./server
    image: gql-server:gql-server_v1
    ports:
      - 3001:4000
