version: "3"

services:
  front-service:
    build: ./frontend
    image: gql-frontend:gql-frontend_v1
    ports:
      - 1234:3000
    depends_on:
      - back-service
  back-service:
    build: ./server
    image: gql-server:gql-server_v1
    ports:
      - 5000:4000
